# Generated by Django 2.2.12 on 2020-05-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200520_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.CharField(max_length=60)),
                ('fecha', models.DateField(blank=True)),
                ('tercero', models.CharField(max_length=60)),
                ('moneda', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
    ]
