# Generated by Django 2.2.12 on 2020-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_geeksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numerodocumento',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
